Frontend user service
CS3219-AY2223S1/cs3219-project-ay2223s1-g60 pull request #27
Opened 2022-09-14 13:25 UTC by drake25122000

Resolves #18 #19 #20 #21

2022-09-15 15:29 UTC, florenciamartina approved these changes
LGTM

2022-09-15 15:41 UTC, erinmayg reviewed
Minor changes, also for frontend, can run:
```npx prettier --write src```
to update coding style for unstaged files

2022-09-15 15:41 UTC, erinmayg commented on .gitignore
> +/user-service/dump.rdb
no newline at EOF

2022-09-15 15:41 UTC, erinmayg commented on frontend/.env
> +CHOKIDAR_USEPOLLING=true
remove .env from commit

2022-09-15 15:41 UTC, erinmayg commented on frontend/src/@types/UserContext.d.ts
> +}
no newline at EOF

2022-09-15 15:41 UTC, erinmayg commented on frontend/src/components/HomePage.tsx
> +export default HomePage;
no newline at EOF

2022-09-15 15:41 UTC, erinmayg commented on frontend/src/components/LoginPage.tsx
> +
remove blank line

2022-09-15 15:41 UTC, erinmayg commented on frontend/src/components/modal/ChangePasswordDialog.tsx
> +
remove blank line

2022-09-15 15:41 UTC, erinmayg commented on user-service/controller/user-controller.js
> +        // }
remove comment

2022-09-15 15:41 UTC, erinmayg commented on user-service/controller/user-controller.js
> +
remove extra blank line

2022-09-15 17:18 UTC, jzwoo requested changes
If possible, try to break the MR into smaller portions, this MR is a little too big

2022-09-15 17:18 UTC, jzwoo commented on frontend/src/App.tsx
> +        <Box display={"flex"} flexDirection={"column"} padding={"4rem"}>
I think its better to add the stylings into the sx prop that material UI provides: https://mui.com/material-ui/react-box/

2022-09-15 17:18 UTC, jzwoo commented on frontend/src/components/SignupPage.tsx
> +    <Box display={"flex"} flexDirection={"column"} width={"30%"}>
Stylings in sx prop

2022-09-29 08:18 UTC, erinmayg approved these changes
LGTM

2022-09-29 08:21 UTC, jzwoo approved these changes
LGTM

2022-09-29 08:21 UTC, merged