Implement history backend
CS3219-AY2223S1/cs3219-project-ay2223s1-g60 pull request #96
Opened 2022-10-31 17:54 UTC by drake25122000

2022-11-01 14:10 UTC, jzwoo requested changes

2022-11-01 14:10 UTC, jzwoo commented on history-service/index.js
> +app.listen(8005, () => console.log("history-service listening on port 8000"));
listening on port 8005

2022-11-01 14:10 UTC, jzwoo commented on history-service/controller/history-controller.js
> +}
new line

2022-11-01 14:10 UTC, jzwoo commented on history-service/model/repository.js
> +  process.env.ENV == "PROD"
i think its '==='

2022-11-02 08:55 UTC, erinmayg approved these changes
LGTM

2022-11-05 18:21 UTC, closed without merging